### ISSUE TITLE
Commands not properly quoted

### ISSUE THREAD

**Issue by segfly** [deitch/mysql-backup#15]
There are a few places where commands are not properly quoted. I noticed this in particular with the `smbclient` when I tried to use a password with spaces:

https://github.com/deitch/mysql-backup/blob/7c8e12b18451f8db04fd6ecf74e1b5cb593b6a05/entrypoint#L104

If I get a chance I'll open a PR, but I couldn't find a quick way to fix this as the current approach is using `UPASS` to also pass in the `-U` flag to `smbclient`:
```
UPASS="-U ${uri[user]}%${uri[password]}"
```

I tried adding escaped quotes within the string but it gave me completely unexpected (and not working) results - there must be some bash-ism I am missing. For now, I am just patching in my own image to remove the `-U` from `UPASS` and then I can quote it properly when the `smbclient` is called:
```
smbclient ... -U "${UPASS}" ...
```

**Comment by deitch** [comment]
> There are a few places where commands are not properly quoted.

Are there places other than password? Would you mind providing links to them?

> when I tried to use a password with spaces:

Ouch. I guess it is a legitimate password, but it is very hard to pass around as env var.

> as the current approach is using UPASS to also pass in the -U flag to smbclient:
> some bash-ism I am missing

Yeah. If you do 

```
smbclient -N //${uri[host]}/${uri[share]} "${UPASS}" ... 
```

then the shell will pass the entire value of `${UPASS}` as a single argument to `smbclient`. Thus, whereas the shell should interpret it as `-U somevalue` and we would have 4 args:

* `smbclient` = `arg[0]`
* `-N` = `arg[1]`
* `<the url>` = `arg[2]`
* `-U user%pass` = `arg[3]`

instead of the desired 

* `smbclient` = `arg[0]`
* `-N` = `arg[1]`
* `<the url>` = `arg[2]`
* `-U` = `arg[3]`
* `user%pass` = `arg[4]`

What you are asking for is to ensure that the argument to `UPASS` is properly handled (i.e. quoted) and the `-U` part is still separate. 

Easiest way is to have two separate vars: `UPASSARG` (always set to `-U` or `""`) and `UPASS` (always set to the value or `""`).

**Comment by segfly** [comment]
@deitch Thanks for merging a fix so quickly!

> Are there places other than password? Would you mind providing links to them?

I was just looking around in general in terms of defensive bash programming. For smbclient: The `-W` flag is not quoted (regardless if a domain is even allowed to have a space). The `//host/share/path` is also not quoted - I think it's possible to have spaces in paths and shares, so this could be an issue.

I also noticed that the awscli parameters are also not quoted. Though I don't know if that poses any specific issues as I don't use the awscli much.

**Comment by deitch** [comment]
> defensive bash programming

That is such a great term!

**Comment by deitch** [comment]
> The -W flag is not quoted (regardless if a domain is even allowed to have a space)

The fix there is the same as with `UPASS`, i.e. 2 separate vars. But like you said, I do not believe domain is allowed to have a space. 

> The //host/share/path is also not quoted - I think it's possible to have spaces in paths and shares, so this could be an issue.

I didn't think it was possible; I thought you needed to convert them into escaped equivalents. Still and all, it cannot hurt to be defensive about it. PR in on that right now.

> awscli parameters are also not quoted

I do not think that poses any issue. I know bucket names cannot include spaces in them [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html), and Amazon strongly discourages using whitespace in object keys but does not restrict it [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html), so we had better escape it.

Good point.

**Comment by deitch** [comment]
Thanks for the suggestions. Done there too.

**Comment by segfly** [comment]
@deitch Thanks!

**Comment by deitch** [comment]
It is nice to have easy ones once in a while. I spend most of my time on very complex ones - personal (process changes, organization incentives, helping appdev and infra get along and join forces, etc.) and technical (building an entire appdev deployment pipeline, or deploying kubernetes from scratch, or solving weird Kafka issues in containers) - so nice to solve something that can be done in a day!
