### ISSUE TITLE
Override TARGET and DB_DUMP_TARGET at runtime

### ISSUE THREAD

**Issue by kabudu** [deitch/mysql-backup#52]
This is my use case:

- Backup database

       // The documentation says this: db_backup_YYYYMMDDHHmm.sql.gz, but the final file doesn't have a .sql.gz suffix
       db_backup_201808051404.gz

- Backup wordpress
- Combine database and wordpress backup into a new backup filename
- Upload new filename backup to S3 in a date namespaced folder structure
       
       original dump target: s3://bucket_name
       new dump target: s3://bucket_name/2018/08/<new_filename>

A workaround for ensuring that the new combined file will be uploaded to S3 is to give it the same name as the original ```TARGET``` and place it in the same path, i.e. ```TMPDIR```, however I would much rather give the resultant file a more descriptive name.

I have not yet found a workaround for my other requirement.

Is there a way of achieving what I want currently?

**Comment by deitch** [comment]
> but the final file doesn't have a .sql.gz suffix

Correct. This probably should be cleaned up, along with a few other documentation errors. Will open a PR shortly.

> A workaround for ensuring that the new combined file will be uploaded to S3 is to give it the same name as the original TARGET and place it in the same path, i.e. TMPDIR, however I would much rather give the resultant file a more descriptive name

So you are thinking to use the [post-backup scripts ](https://github.com/deitch/mysql-backup#backup-pre-and-post-processing) to run your Wordpress and combine them, but you want to use a different name that is more reflective (or perhaps have 2 files). But the "uploader" part that moves the temporary `TARGET` into another file/dir/S3/SMB/etc. only takes `TARGET`. Is that it?

**Comment by kabudu** [comment]
> But the "uploader" part that moves the temporary TARGET into another file/dir/S3/SMB/etc. only takes TARGET. Is that it?

Effectively yes. Given that in S3, the folder structure isn't really a folder structure but an object key, if you could use whatever name you wanted for the final backup file at **runtime**, it would be uploaded to the path defined by the custom name, which in my case could be:

*Actual filename on local disk:* db_backup_201808051404.gz 
*Upload filename:* 2018/08/my-combined-files.gz

OR as you suggested, support having multiple files, so the "uploader" part would upload everything inside a specific ```upload target``` folder. Of course with this approach, the restore functionality will also need to support multiple files, only restoring mysql files and leaving all other files to the ```post-restore``` script.

**Comment by kabudu** [comment]
> Or is it that you would modify the TARGET as part of your post-backup script, and then give it a different remote name?

Exactly! :)

**Comment by deitch** [comment]
Something bothers me about this, modifying things directly like that, but I cannot figure out what it is, and as long as it is an option and non-destructure, why not?

We would need to figure out how you name the target file. E.g. You couldn't always call it `foo.tgz`, because then you lose the entire date-based naming convention. We could use some templating system, but that seems messy too.

What about a "name processor"? We already have pre-backup and post-backup directories, why not a name processor? If `/scripts.d/target.sh` exists and is executable, then it is called and the value of stdout is the new name for the remote file(s). We already pass it (from the docs):

* `DUMPFILE`: full path in the container to the output file
* `NOW`: date of the backup, as included in `DUMPFILE` and given by `date -u +"%Y%m%d%H%M%S"`

So it should be able to construct anything it wants. I like the idea of passing all control to that script, so we don't have to mess with templates.

Thoughts?

**Comment by deitch** [comment]
You want to open a PR on it?

**Comment by kabudu** [comment]
> You want to open a PR on it?

Sure, I'll put something together as soon as I can.

**Comment by kabudu** [comment]
Closing as related PR has been merged.
