### ISSUE TITLE
Question about variables passed

### ISSUE THREAD

**Issue by Gymnae** [deitch/mysql-backup#7]
Hi @deitch ,
thank you for providing such a helpful project.
Before I'll fire it up to put a mysqldump into the data container which is backed up via duplicity in another container (I like to go micro-service as much as possible), I' need to clarify something for me:
`-v /local/file/path:/db `

Should this be a path used by the database container or a temporary cache path for `mysql-backup`? 

As I understand this image needs a linked connection to a running database container and a location to store the resulting dumb. My database containers are all working with docker volumes.

Maybe it's just to early in the morning for me.

Cheers

**Comment by deitch** [comment]
Hi @Gymnae thank you, and we thank the client with whom I was working at the time who agreed to open-source the project. :-)

> Should this be a path used by the database container or a temporary cache path for mysql-backup?

Neither, actually. mysql-backup can back up to multiple places, any of:

* local filesystem
* SMB share
* S3 

If you decide to go to the local filesystem, it doesn't do you much good if the backup is stored inside the container. So in the example, we mount it so that the backup is stored on a directory mounted *outside* the container. But if you are backing up to S3 or SMB, then you don't need the `-v` mount at all.

Inside the backup, it does store it in a temporary place before sending it to the final file, SMB or S3, but that doesn't need to be mounted.

I have another project that supports saving it to a git server. I am hoping to merge that in here as well.
