### ISSUE TITLE
Auto purge of older backups?

### ISSUE THREAD

**Issue by Gymnae** [deitch/mysql-backup#9]
Is there the possibility to add a purge functionality? Like a logic that check the backup destination and deletes old backups following a set rule? 
For example only keep X most recents backups, or delete all backups older than X months?

Cheers :)

**Comment by deitch** [comment]
Sort of Time Machine logic built in? I do like the idea, although I wonder if it is better as a separate container. 

How would the API look? What would the command-line be? I imagine there are several modes:

1. "prune-only": don't run backups, just prune and exit
2. "prune-always": don't run backups, prune and check prune every X mins or seconds or midnight or whatever
3. "prune-while-backup": have the backups run and have the pruning in the same container.

I somewhat _dislike_ 3, for the reasons above. If I am managing backups, I prefer to know that my backup process and pruning process are distinct. Microservices orientation. I am fine with it being the same image (I like that; code reuse), but different flags run different ways.

OK, what would the call be? How would we determine options?

**Comment by Gymnae** [comment]
In the truest sense of micro services this would indeed be another service, but so would be uploading to s3. I think, just like it's done with mailserver packages or some webserver containers: What works together, belongs together. I bundle PHP with nginx, for example

What would probably work is a check for the existence of backups in the target folder and their naming.
if a date based pruning is used, the filename determines the action. very simplistic and not working, if files get removed or renamed.
keeping a database of backups and hashing the files and checking for backups on an md5 basis would require persistent storage for the backup container itself (unless this file resides in the backup target)

The call could be an environment variable:
`-e PRUNE_MAXAGE=6Mo`
`-e PRUNE_KEEP=3`
`-e PRUNE_INTERACTIVE=no`

Then a simple rm process would run after the backup.

Does the AWS API give info on storage class? Pruning too often on Glacier might incur higher costs than simply keeping the files there

**Comment by deitch** [comment]
I don't see anything that would prevent it from checking the target storage to see if anything is there. Again, it makes a lot of sense to make it a different command-line option for a different invocation:

* backup: if `DB_DUMP_TARGET` is set
* restore: if `DB_RESTORE_TARGET` is set
* prune: if `PRUNE_TARGET` is set

One container runs backup (long-running or one-off), another runs prunes (long-running or one-off).

> keeping a database of backups and hashing the files and checking for backups on an md5 basis would require persistent storage for the backup container itself

Yeah, that is the larger question, isn't it? The backup service is, essentially, a dumb (well, stateless) service. Other than keeping track of sources, destinations and when to run the next backup, it doesn't keep anything in state. I have little desire to start creating that now. One step at a time here.

OK, let's start with prune as a separate set of env options. Keep them parallel to the long-running dump options:

* `PRUNE_FREQ`: How often to prune, in minutes. Defaults to 1440 minutes, or once per day.
* `PRUNE_BEGIN`: What time to do the first prune. Defaults to immediate.
* `DB_DUMP_DEBUG`: If set to true, print copious shell script messages to the container log. Otherwise only basic messages are printed.
* `PRUNE_TARGET`: path to the location of the dumps. Identical to that used for `DB_DUMP_TARGET`

This makes sense. 

So.. want to open a PR for this?

**Comment by juanluisbaptiste** [comment]
This is more easily done with a separate script using the new post-backup processing plugin system and an external tool to rotate backups like [rotate-backups](https://rotate-backups.readthedocs.io/en/latest/), that's what I use.

**Comment by deitch** [comment]
> This is more easily done with a separate script using the new post-backup processing plugin system and an external tool to rotate backups like rotate-backups

Good point. Any comment on it, @Gymnae ?

**Comment by pprazzi** [comment]
what @juanluisbaptiste suggested works fine. As an example my Dockerfile

```
FROM deitch/mysql-backup

RUN pip3 install rotate-backups
COPY rotate-dbbackups.sh /scripts.d/post-backup/rotate-dbbackups.sh
RUN chmod +x /scripts.d/post-backup/rotate-dbbackups.sh

ENTRYPOINT ["/entrypoint"]
```

where rotate-dbbackups.sh looks like this:

```
#!/bin/bash
/usr/bin/rotate-backups $ROTATE_OPTIONS /db
```

in your docker-compose you can now use an additional environment var like this 

`- ROTATE_OPTIONS=--daily=7 --weekly=4 --monthly=1 --prefer-recent`

**Comment by johannrichard** [comment]
Instead of re-building / baking this in, you could also hint at an existing other Docker image that bundles `rotate-backups` almost as suggested:

https://hub.docker.com/r/cismet/rotated-delete/~/dockerfile/

**Comment by deitch** [comment]
This always is a tough question. When do you add functionality to a core product vs using another product next to it.

This has been open for a long time. I am going to close it out for now in favour of a "sidecar" that rotates. If someone wants to open a PR that does not overcomplicate the core product, definitely open to it.

FYI, looking to convert this from script to golang binary. When I can find time (as I just implemented fat32, gpt, mbr in golang, in the process of ext4, also boot sectors, etc. - and all on the side of a day job...).
